### ISSUE TITLE
BSOD like TDL

### ISSUE THREAD

**Issue by 1424667164** [not-wlan/drvmap#4]
I just create a driver with "IoCreateDriver " but do nothing...
it BSOD about 30 min or one hour.
is this normal?  
win10 16299

**Comment by NotAdam** [comment]
working as intended

**Comment by 1424667164** [comment]
any other way to more time run before BSOD? 
   -_-    -----------   -_-
it`s too short time. (^_^)

**Comment by NotAdam** [comment]
you need to buy the drvmap pro:tm: license which increases the max runtime to 8h per session, @not-wlan can help you with that

**Comment by 1424667164** [comment]
ok, tk
